# name: Build & Deploy

# on:
#   push:
#     branches:
#       - master
#       - qa

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         branch: [master, qa]

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 14.x

#     - name: Install NPM packages
#       run: npm ci

#     - name: Build project
#       run: npm run build

#     - name: Configure CNAME
#       run: |
#         if [ "${{ matrix.branch }}" == "master" ]; then
#           echo "adme.com.ar" > ./build/CNAME
#         elif [ "${{ matrix.branch }}" == "qa" ]; then
#           echo "qa.adme.com.ar" > ./build/CNAME
#         fi

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build
#         publish_branch: ${{ matrix.branch == 'master' && 'gh-pages' || 'gh-pages-qa' }}
name: Build & Deploy

on:
  push:
    branches:
      - master
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, qa]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Configure CNAME
      run: |
        if [ "${{ matrix.branch }}" == "master" ]; then
          echo "adme.com.ar" > ./build/CNAME
        elif [ "${{ matrix.branch }}" == "qa" ]; then
          echo "qa.adme.com.ar" > ./build/CNAME
        fi

    - name: Deploy to GitHub Pages (Production)
      if: matrix.branch == 'master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        keep_files: true

    - name: Deploy to GitHub Pages (QA)
      if: matrix.branch == 'qa'
      run: |
        # Clonar la rama gh-pages en un directorio temporal
        git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages

        # Crear o limpiar el subdirectorio qa/
        mkdir -p gh-pages/qa
        rm -rf gh-pages/qa/*

        # Mover el contenido construido al subdirectorio qa/
        mv ./build/* gh-pages/qa/

        # Configurar el usuario de Git para el commit
        cd gh-pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Hacer commit y push de los cambios
        git add .
        git commit -m "Deploy QA to gh-pages/qa"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
