# name: Build & Deploy

# on:
#   push:
#     branches:
#       - master
#       - qa

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         branch: [master, qa]

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 14.x

#     - name: Install NPM packages
#       run: npm ci

#     - name: Build project
#       run: npm run build

#     - name: Configure CNAME
#       run: |
#         if [ "${{ matrix.branch }}" == "master" ]; then
#           echo "adme.com.ar" > ./build/CNAME
#         elif [ "${{ matrix.branch }}" == "qa" ]; then
#           echo "qa.adme.com.ar" > ./build/CNAME
#         fi

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build
#         publish_branch: ${{ matrix.branch == 'master' && 'gh-pages' || 'gh-pages-qa' }}


name: Build & Deploy

on:
  push:
    branches:
      - master
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, qa]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Set environment variable
      run: |
          if [ "${{ matrix.branch }}" == "master" ]; then
            echo "REACT_APP_ENV=production" >> $GITHUB_ENV
          elif [ "${{ matrix.branch }}" == "qa" ]; then
            echo "REACT_APP_ENV=qa" >> $GITHUB_ENV
          fi
  
    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Configure CNAME
      run: |
        if [ "${{ matrix.branch }}" == "master" ]; then
          echo "adme.com.ar" > ./build/CNAME
        elif [ "${{ matrix.branch }}" == "qa" ]; then
          echo "qa.adme.com.ar" > ./build/CNAME
        fi

    - name: Set up Git user
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

    - name: Deploy to GitHub Pages (Production)
      if: matrix.branch == 'master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages

    - name: Deploy to Separate QA Repository
      if: matrix.branch == 'qa'
      run: |
          cd ./build
          git init
          git remote add origin https://x-access-token:${{ secrets.ADME_CORP_QA_SECRET }}@github.com/mariogruizdiaz/insights-corp-qa.git
          git add -f .
          git commit -m "Deploy QA from QA branch"
          git push origin HEAD:master --force
