name: Deploy QA

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Configure CNAME for QA
      run: echo "qa.adme.com.ar" > ./build/CNAME

    - name: Deploy to GitHub Pages (QA)
      run: |
        # Clonar la rama gh-pages en un directorio temporal usando el token de GitHub
        git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

        # Crear o limpiar el subdirectorio qa/
        mkdir -p gh-pages/qa
        rm -rf gh-pages/qa/*

        # Mover el contenido construido al subdirectorio qa/
        mv ./build/* gh-pages/qa/

        # Configurar el usuario de Git para el commit
        cd gh-pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        # Hacer commit y pull para evitar conflictos
        git add .
        git commit -m "Deploy QA to gh-pages/qa"
        git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
